-- Migration đầu tiên của feature 000-walking-skeleton: dựng năm bảng của hai module
-- `catalog` (category, product, product_image) và `stock` (stock, stock_ledger).
--
-- AD-1 — bất biến trung tâm "tồn kho không bao giờ âm" GIỮ NGUYÊN ở đây bằng
-- CONSTRAINT "stock_quantity_non_negative" CHECK (quantity >= 0) trên bảng `stock`. Bất biến
-- sống trong ràng buộc CHECK của database, không trong code ứng dụng.
--
-- AD-24 — quan hệ vượt biên module GIỮ NGUYÊN đúng như sau: `stock.product_id` ON DELETE
-- CASCADE; `stock_ledger.product_id` ON DELETE RESTRICT (sổ cái là bản kiểm toán — xoá một
-- Product có dòng sổ cái phải bị chặn ở tầng dữ liệu); `stock_ledger.order_id` là giá trị
-- TRẦN, KHÔNG có khoá ngoại (module `stock` không được biết module `ordering` tồn tại).
--
-- Mọi migration sau này chạm bảng `stock`/`stock_ledger` phải nói rõ nó giữ nguyên (hoặc thay
-- đổi có chủ đích) những ràng buộc trên (AD-25).
CREATE TYPE "public"."stock_ledger_reason" AS ENUM('order_placed', 'order_cancelled', 'manual_adjustment');--> statement-breakpoint
CREATE TABLE "category" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"name_normalized" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "product" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"category_id" bigint,
	"name" text NOT NULL,
	"name_normalized" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"price" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_price_non_negative" CHECK ("product"."price" >= 0)
);
--> statement-breakpoint
CREATE TABLE "product_image" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"product_id" bigint NOT NULL,
	"path" text NOT NULL,
	"position" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock" (
	"product_id" bigint PRIMARY KEY NOT NULL,
	"quantity" integer NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "stock_quantity_non_negative" CHECK ("stock"."quantity" >= 0)
);
--> statement-breakpoint
CREATE TABLE "stock_ledger" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_ledger_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"product_id" bigint NOT NULL,
	"delta" integer NOT NULL,
	"quantity_after" integer NOT NULL,
	"reason" "stock_ledger_reason" NOT NULL,
	"order_id" bigint,
	"actor_account_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stock_ledger_delta_non_zero" CHECK ("stock_ledger"."delta" <> 0),
	CONSTRAINT "stock_ledger_quantity_after_non_negative" CHECK ("stock_ledger"."quantity_after" >= 0)
);
--> statement-breakpoint
ALTER TABLE "product" ADD CONSTRAINT "product_category_id_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_image" ADD CONSTRAINT "product_image_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock" ADD CONSTRAINT "stock_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_ledger" ADD CONSTRAINT "stock_ledger_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE restrict ON UPDATE no action;